<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form id="miForm" action="<?= URL . 'Producto/save' ?>" method="post">
                <input type="hidden" name="idproducto" value="<?= $data->IdProducto ?>">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">

                            <label for="marca">Marca</label>

                            <select action="" name="idproducto" id="inputIdMarca" class="form-control">
                                <?php foreach ($marca as $row) : ?>

                                    <option value="">
                                        <?= $row->Nombre ?>
                                    </option>;
                                <?php endforeach; ?>

                            </select>


                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">

                            <label for="categoria">Categoria</label>

                            <select action="" name="idproducto" id="inputIdCategoria" class="form-control">
                                <?php foreach ($categorias as $row) : ?>

                                    <option value="">
                                        <?= $row->Nombre ?>
                                    </option>;
                                <?php endforeach; ?>

                            </select>

                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="proveedor">Proveedor</label>
                            <select action="" name="idproducto" id="inputIdProveedor" class="form-control">
                                <?php foreach ($proveedores as $row) : ?>
                                    <option value="">
                                        <?= $row->Nombre ?>
                                    </option>;
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="id_nombre">Nombre</label>
                            <input type="text" name="nombre" id="id_nombre" class="form-control" value="<?= $data->Nombre ?>">
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <label for="id_descripcion">Descripción</label>
                            <input type="text" name="descripcion" id="id_descripcion" class="form-control" value="<?= $data->Descripcion ?>">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">

                            <input type="checkbox" name="estado" id="idestado" class="form-check-input" <?= ($data->Estado == 1) ? "checked" : "" ?> <label class="form-check-label" for="exampleCheck1">Estado</label>
                        </div>
                        <br>
                        <br>
                    </div>
                    <div class="col-sm-8">
                        <div id="mis_errores"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Guardar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>