<?php $this->layout('../layouts/layout', ['title' => 'alcventassmvc|PRODUCTO']) ?>

<?php $this->push('styles'); ?>
<!-- //link de css  -->
<?php $this->end(); ?>
<?php $this->push('contents'); ?>

<div class="container">
    <h1>Productos</h1>
    <div class="row">
        <div class="col-sm-4">
            <a is-modal="true" href="<?= URL . 'producto/detail' ?>" class="btn btn-primary btn-block">Nuevo</a>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-sm-12">
            <table class="table">
                <thead>
                    <tr>
                        <th style="width: 10%;">ID</th>
                        <th style="width: 15%;">Marca</th>
                        <th style="width: 15%;">Categoria</th>
                        <th style="width: 15%;">Proveedor</th>
                        <th style="width: 15%;">NOMBRE</th>
                        <th style="width: 20%;">DESCRIPCION</th>
                        <th style="width: 10%;">Estado</th>
                        <th style="width: 10%;"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data as $row) : ?>
                        <tr>
                            <td><?= $row->IdProducto ?></td>
                            <td><?= $row->marcas->Nombre ?></td>
                            <td><?= $row->categorias->Nombre ?></td>
                            <td><?= $row->proveedores->Nombre ?></td>
                            <td><?= $row->Nombre ?></td>
                            <td><?= $row->Descripcion ?></td>
                            <td><?= $row->Estado ?></td>
                            <a href=""></a>
                            <td>
                                <a is-modal="true" href="<?= URL . "producto/detail/{$row->IdProducto}" ?>" title="Editar" class="btn btn-sm btn-primary"> <i class="fas fa-pencil-alt"></i></a>

                                <a href="<?= URL . "producto/delete/{$row->IdProducto}" ?>" title="Eliminar" class="btn btn-sm btn-danger" onclick="return confirm('¿Está seguro de eliminar este registro?')"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php $this->stop(); ?>

<?php $this->start('myModal') ?>

<?php

$title = 'Producto Detalle - Insertar';
$size = GRANDE;
include MAINPATH . 'app/views/layouts/partials/_modalGenerico.phtml';
?>
<?php $this->stop(); ?>

<?php $this->push('scripts'); ?>


<script src="<?= URL . 'js/scripts/modal_crud.js' ?>"></script>
<?php $this->end(); ?>