<?php
$this->layout('../layouts/layout', [
    'title' => 'ALCVentas | Inicio'
]);

?>

<?php $this->push('styles') ?>

<?php $this->end() ?>

<?php $this->start('contents') ?>
<?php include MAINPATH . 'app/views/layouts/partials/_hero.phtml' ?>
<div class="container">
    <h1>Alcides Salazar Rojas</h1>
</div>
<?php include MAINPATH . 'app/views/layouts/partials/_portafolio.phtml' ?>
<?php $this->stop() ?>

<?php $this->push('scripts') ?>

<?php $this->end() ?>