<!-- About -->
<section class="container-fluid about" id="about">
    <div class="container">
        <div class="title_block">
            <h2>Who we are</h2>
        </div>
        <div class="row">
            <div class="col-6">
                <p>Mauris vestibulum est id eros bibendum, consequat efficitur ipsum imperdiet. Aenean turpis velit, accumsan mollis lacinia ac, consequat eu ipsum. Nulla blandit nunc a volutpat facilisis. Nullam pellentesque tellus vel sollicitpharetra. Sed vehicula accumsan mi eget auctor.</p>
            </div>
            <div class="col-6">
                <p>Mauris vestibulum est id eros bibendum, consequat efficitur ipsum imperdiet. Aenean turpis velit, accumsan mollis lacinia ac, consequat eu ipsum. Nulla blandit nunc a volutpat facilisis. Nullam pellentesque tellus vel sollicitpharetra. Sed vehicula accumsan mi eget auctor.</p>
            </div>
        </div>
    </div>
</section>