<!-- Achievments -->
<div class="container-fluid achievments">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col info_achievments animate-math">
                <i class="ic-achievments icon-layers"></i>
                <div class="data_achievments">145</div>
                <p>Happy Clients</p>
            </div>
            <div class="col info_achievments">
                <i class="ic-achievments icon-bubbles"></i>
                <p class="data_achievments">394</p>
                <p>Giving Support</p>
            </div>
            <div class="col info_achievments">
                <i class="ic-achievments icon-trophy"></i>
                <p class="data_achievments">268</p>
                <p>Projects Done</p>
            </div>
            <div class="col info_achievments">
                <i class="ic-achievments icon-star"></i>
                <p class="data_achievments">12</p>
                <p>Awords</p>
            </div>
        </div>
    </div>
</div>