<!-- Blog -->
<section class="container-fluid blog" id="blog">
    <div class="container">
        <div class="title_block">
            <h2>Latest news blog</h2>
        </div>
        <div class="row">
            <div class="col-md-4 last_blog">
                <div class="col image_service blog">
                    <img src="images/blog-foto-1.jpg" alt="blog-foto">
                    <div class="blog_more">
                        <a href="blog-single.html" class="bnt_plus" aria-label="read-more"></a>
                    </div>
                </div>
                <h3>Clean and minimal</h3>
                <span>category blog / 01.01.2019</span>
                <p>Interactively whiteboard cost effective solutions through world-class applications. Conveniently grow team driven value</p>
                <a href="blog-single.html">read more</a>
            </div>
            <div class="col-md-4 last_blog">
                <div class="col image_service blog">
                    <img src="images/blog-foto-2.jpg" alt="blog-foto">
                    <div class="blog_more">
                        <a href="blog-single.html" class="bnt_plus" aria-label="read-more"></a>
                    </div>
                </div>
                <h3>What is real fashion?</h3>
                <span>category blog / 01.01.2019</span>
                <p>Interactively whiteboard cost effective solutions through world-class applications. Conveniently grow team driven value</p>
                <a href="blog-single.html">read more</a>
            </div>
            <div class="col-md-4 last_blog">
                <div class="col image_service blog">
                    <img src="images/blog-foto-3.jpg" alt="blog-foto">
                    <div class="blog_more">
                        <a href="blog-single.html" class="bnt_plus" aria-label="read-more"></a>
                    </div>
                </div>
                <h3>Dancing on the moon</h3>
                <span>category blog / 01.01.2019</span>
                <p>Interactively whiteboard cost effective solutions through world-class applications. Conveniently grow team driven value</p>
                <a href="blog-single.html">read more</a>
            </div>
        </div>
    </div>
</section>