<!-- Clients -->
<section class="container-fluid clients" id="clients">
    <div class="container">
        <div class="row justify-content-between">
            <img src="images/brand-logo1.png" alt="clients">
            <img src="images/brand-logo2.png" alt="clients">
            <img src="images/brand-logo3.png" alt="clients">
            <img src="images/brand-logo4.png" alt="clients">
            <img src="images/brand-logo5.png" alt="clients">
            <img src="images/brand-logo6.png" alt="clients">
        </div>
    </div>
</section>