<!-- Contact -->
<section class="container-fluid contact" id="contact">
    <div class="container">
        <div class="title_block">
            <h2>Get in touch</h2>
        </div>
        <div class="row">
            <div class="col-md-6 col-lg-6">
                <p>Cras sit amet mollis odio. Aliquam ac ante eu mauris tincidunt fermentum sit amet sed mauris. Proin tristique lacus sit amet ante hendrerit iaculis. </p>
                <p><i class="fas fa-phone"></i> +790 876 554 2</p>
                <p><i class="fas fa-phone"></i> +794 835 608 8</p>
                <p><i class="fas fa-envelope"></i> pixelvision@mail.com</p>
                <p><i class="fas fa-map-marker-alt"></i> England, London, Bakery St., 34</p>
            </div>
            <div class="col-md-6 col-lg-6" id="contactWrapper">
                <form class="contact-form" id="contactform">
                    <div class="row connection-form">
                        <div class="col-md-6">
                            <input type="text" aria-label="First Name" placeholder="First Name" id="first-name" size="40" aria-invalid="false" />
                        </div>
                        <div class="col-md-6">
                            <input type="text" aria-label="Last Name" placeholder="Last Name" id="last-name" size="40" aria-invalid="false" />
                        </div>
                    </div>
                    <div class="row connection-form">
                        <div class="col-md-6">
                            <input type="text" aria-label="Subject" name="subject" id="subject" size="40" aria-invalid="false" placeholder="Subject" />
                        </div>
                        <div class="col-md-6">
                            <input type="text" aria-label="Email" placeholder="Email" id="email" size="40" aria-invalid="false" />
                        </div>
                    </div>
                    <div class="col-md-12">
                        <textarea name="message" aria-label="Message" placeholder="Message" id="message" aria-invalid="false"></textarea>
                    </div>
                    <div class="col-md-12">
                        <input type="button" value="Send" aria-label="Send" class="btn_send" id="submit" onClick="return check_values();" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>