<!-- Footer -->
<div class="container-fluid footer">
    <div class="container">
        <div class="row footer_info">
            <div class="col-md-4 col-sm-12">
                <p class="logo_footer title_col_footer"><span></span>By ALC</p>
                <p>Mauris vestibulum est id eros bibendum elsec consequat efficitur ipsum imperdiet. Aenean turpis velit Praesent sit amet consequat dolor</p>
                <div class="row social_network footer justify-content-start">
                    <a href="main.html" aria-label="social-link"><i class="fab fa-facebook-f"></i></a>
                    <a href="main.html" aria-label="social-link"><i class="fab fa-twitter"></i></a>
                    <a href="main.html" aria-label="social-link"><i class="fab fa-pinterest-p"></i></a>
                    <a href="main.html" aria-label="social-link"><i class="fab fa-tumblr"></i></a>
                </div>
            </div>
            <div class="col-md-3 col-sm-12">
                <p class="title_col_footer">Contactos</p>
                <p>+794 835 608 8</p>
                <p>pixelvision@mail.com</p>
                <p>England, London, Bakery St., 34</p>
            </div>
            <div class="col-md-2 col-sm-12">
                <p class="title_col_footer">Somos</p>
                <p><a href="main.html">Service</a></p>
                <p><a href="main.html">Portfolio</a></p>
                <p><a href="main.html">Blog</a></p>
            </div>
            <div class="col-md-3 col-sm-12">
                <p class="title_col_footer">Informacion</p>
                <p><a href="main.html">Terms & Condition</a></p>
                <p><a href="main.html">Privacy Policy</a></p>
            </div>
        </div>
        <div class="copyright-footer">
            <p>Copyright 2021, By ALC. Todos los derechos reservados.</p>
        </div>
    </div>
</div>