<!-- Navbar -->

<nav class="navbar navbar-expand-lg navbar-light navbar navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="home">By alc</a>
        <button class="navbar-toggler nav-toggle" type="button" name="nav_toggle" id="toggle" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="bar-top"></span>
            <span class="bar-mid"></span>
            <span class="bar-bot"></span>
        </button>
        <div class="navbar-collapse overlay" id="overlay">
            <ul class="navbar-nav overlay-menu">
                <li class="nav-item">
                    <a class="nav-link" href="home">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="categoria">Categorias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="marca">Marcas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="producto">Productos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="proveedor">Proveedores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="tipousuario">Usuarios</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="home">Desarrolador</a>
                </li>
            </ul>
        </div>
    </div>
</nav>