<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
    <div class="container">
        <a class="navbar-brand" href="main.html#home">By alc</a>
        <button class="navbar-toggler nav-toggle" type="button" name="nav_toggle" id="toggle" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="bar-top"></span>
            <span class="bar-mid"></span>
            <span class="bar-bot"></span>
        </button>
        <div class="navbar-collapse overlay" id="overlay">
            <ul class="navbar-nav overlay-menu">
                <li class="nav-item">
                    <a class="nav-link" href="../../home/index.phtml">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="main.html#about">Acerca de</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="main.html#portfolio">Portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="main.html#clients">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="main.html#staff">Equipo</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="main.html#blog">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="main.html#contact">Contactos</a>
                </li>
            </ul>
        </div>
    </div>
</nav>