<!-- Hero -->
<section class="container-fluid top" id="home">
    <div class="container">
        <div class="slogan typed_wrap">
            <h1>Somos <span class="typed"></span></h1>
            <div class="typed-strings" style="display: none;">
                <p>Compañia</p>
                <p>Agencia</p>
                <p>Creativo</p>
            </div>
            <p>Sólo hay dos maneras de vivir la vida. Uno es como si nada fuera un milagro<br>Segundo - si los milagros están por todas partes</p>
        </div>
        <div class="scroll-bottom"><a href="main.html#about" class="scroll-icon"></a></div>
    </div>
</section>