<!-- Portfolio -->
<section class="container-fluid portfolio" id="portfolio">
    <div class="container">
        <div class="row menu_portfolio justify-content-between">
            <div class="title_block">
                <h2>Latest project</h2>
            </div>
            <div id="filters" class="button-group">
                <button class="btn_filter is-checked" data-filter="*">All</button>
                <button class="btn_filter" data-filter=".design">Design</button>
                <button class="btn_filter" data-filter=".photo">Photo</button>
                <button class="btn_filter" data-filter=".branding">Branding</button>
            </div>
        </div>
        <div class="no-gutter row" id="posts">
            <div class="item photo col-sm-6 col-md-6 col-lg-4">
                <div class="item-wrap">
                    <img class="img-responsive" src="images/foto-1.jpg" alt="foto-portfolio">
                    <div class="view_progect">
                        <div>
                            <hr>
                            <h3>Project Title</h3>
                            <p>Web Design</p>
                            <a class="link-details" href="portfolio-details.html"><i class="fas fa-link"></i></a>
                            <a class="link-fullscreen" data-fancybox="images" href="images/foto-1.jpg" data-caption="Project Title"><i class="fas fa-search"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item photo col-sm-6 col-md-6 col-lg-4">
                <div class="item-wrap">
                    <img class="img-responsive" src="images/foto-2.jpg" alt="foto-portfolio">
                    <div class="view_progect">
                        <div>
                            <hr>
                            <h3>Project Title</h3>
                            <p>Photo</p>
                            <a class="link-details" href="portfolio-details.html"><i class="fas fa-link"></i></a>
                            <a class="link-fullscreen" data-fancybox="images" href="images/foto-2.jpg" data-caption="Project Title"><i class="fas fa-search"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item design col-sm-6 col-md-6 col-lg-4">
                <div class="item-wrap">
                    <img class="img-responsive" src="images/foto-4.jpg" alt="foto-portfolio">
                    <div class="view_progect">
                        <div>
                            <hr>
                            <h3>Project Title</h3>
                            <p>Design</p>
                            <a class="link-details" href="portfolio-details.html"><i class="fas fa-link"></i></a>
                            <a class="link-fullscreen" data-fancybox="images" href="images/foto-4.jpg" data-caption="Project Title"><i class="fas fa-search"></i></a>
                        </div>
                    </div>
                    </a>
                </div>
            </div>
            <div class="item photo col-sm-6 col-md-6 col-lg-4">
                <div class="item-wrap">
                    <img class="img-responsive" src="images/foto-3.jpg" alt="foto-portfolio">
                    <div class="view_progect">
                        <div>
                            <hr>
                            <h3>Project Title</h3>
                            <p>Photo</p>
                            <a class="link-details" href="portfolio-details.html"><i class="fas fa-link"></i></a>
                            <a class="link-fullscreen" data-fancybox="images" href="images/foto-3.jpg" data-caption="Project Title"><i class="fas fa-search"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item branding col-sm-6 col-md-6 col-lg-4">
                <div class="item-wrap">
                    <img class="img-responsive" src="images/foto-5.jpg" alt="foto-portfolio">
                    <div class="view_progect">
                        <div>
                            <hr>
                            <h3>Project Title</h3>
                            <p>Branding</p>
                            <a class="link-details" href="portfolio-details.html"><i class="fas fa-link"></i></a>
                            <a class="link-fullscreen" data-fancybox="images" href="images/foto-5.jpg" data-caption="Project Title"><i class="fas fa-search"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>