<!-- Service -->
<div class="container-fluid service">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="row title_service">
                    <i class="icon_dev"></i>
                    <h3>Web development</h3>
                </div>
                <p>Mauris vestibulum est id eros bibendum elsec consequat efficitur ipsum imperdiet. Aenean turpis velit</p>
                <div class="image_service web">
                    <img src="images/photo-1427751840561-9852520f8ce8.jpg" alt="web">
                </div>
            </div>
            <div class="col-md-4">
                <div class="row title_service">
                    <i class="icon_brand"></i>
                    <h3>Branding</h3>
                </div>
                <p>Mauris vestibulum est id eros bibendum elsec consequat efficitur ipsum imperdiet. Aenean turpis velit</p>
                <div class="image_service brand">
                    <img src="images/photo-1449247526693-aa049327be54.jpg" alt="brand">
                </div>
            </div>
            <div class="col-md-4">
                <div class="row title_service">
                    <i class="icon_design"></i>
                    <h3>UI/UX design</h3>
                </div>
                <p>Mauris vestibulum est id eros bibendum elsec consequat efficitur ipsum imperdiet. Aenean turpis velit</p>
                <div class="image_service ui">
                    <img src="images/jwimshwif14-jeff-sheldon.jpg" alt="ui">
                </div>
            </div>
        </div>
    </div>
</div>