<!-- Staff -->
<section class="container-fluid staff" id="staff">
    <div class="container">
        <div class="title_block">
            <h2>The best staff</h2>
        </div>
        <div class="our_staff">
            <div class="row person first justify-content-end">
                <div class="col-4 about_staff">
                    <p class="name_staff">Christina Thompson</p>
                    <p class="profession_staff">Web designer</p>
                    <p>Mauris vestibulum est id eros bibendum elsec consequat efficitur ipsum imperdiet Aenean</p>
                    <div class="row social_network justify-content-end">
                        <a href="main.html" aria-label="social-link"><i class="fab fa-facebook-f"></i></a>
                        <a href="main.html" aria-label="social-link"><i class="fab fa-twitter"></i></a>
                        <a href="main.html" aria-label="social-link"><i class="fab fa-pinterest-p"></i></a>
                        <a href="main.html" aria-label="social-link"><i class="fab fa-tumblr"></i></a>
                    </div>
                </div>
                <div class="col-5 img_staff">
                    <img src="images/persona1.jpg" alt="persona">
                </div>
            </div>
            <div class="row person center justify-content-start">
                <div class="col-5 img_staff">
                    <img src="images/persona2.jpg" alt="persona">
                </div>
                <div class="col-4 about_staff">
                    <p class="name_staff">Alissia Cronenberg</p>
                    <p class="profession_staff">fashion blogger</p>
                    <p>Mauris vestibulum est id eros bibendum elsec consequat efficitur ipsum imperdiet Aenean</p>
                    <div class="row social_network justify-content-start">
                        <a href="main.html" aria-label="social-link"><i class="fab fa-facebook-f"></i></a>
                        <a href="main.html" aria-label="social-link"><i class="fab fa-twitter"></i></a>
                        <a href="main.html" aria-label="social-link"><i class="fab fa-pinterest-p"></i></a>
                        <a href="main.html" aria-label="social-link"><i class="fab fa-tumblr"></i></a>
                    </div>
                </div>
            </div>
            <div class="row person justify-content-end">
                <div class="col-4 about_staff">
                    <p class="name_staff">Emma Taylor</p>
                    <p class="profession_staff">Web designer</p>
                    <p>Mauris vestibulum est id eros bibendum elsec consequat efficitur ipsum imperdiet Aenean</p>
                    <div class="row social_network justify-content-end">
                        <a href="main.html" aria-label="social-link"><i class="fab fa-facebook-f"></i></a>
                        <a href="main.html" aria-label="social-link"><i class="fab fa-twitter"></i></a>
                        <a href="main.html" aria-label="social-link"><i class="fab fa-pinterest-p"></i></a>
                        <a href="main.html" aria-label="social-link"><i class="fab fa-tumblr"></i></a>
                    </div>
                </div>
                <div class="col-5 img_staff">
                    <img src="images/persona5.jpg" alt="persona">
                </div>
            </div>
        </div>
    </div>
</section>