<!-- Statements -->
<div class="container-fluid statements">
    <div class="container">
        <div class="owl-carousel owl-statements">
            <div class="item">
                <p class="text_statements">Mauris vestibulum est id eros bibendum, consequat efficitur ipsum imperdiet. Aenean turpis velit, accumsan mollis lacinia ac, consequat eu ipsum. Nulla blandit nunc a volutpat facilisis. Nullam pellentesque tellus vel sollicitpharetra. Sed vehicula accumsan mi eget auc </p>
                <p class="name_statements">Christina Thompson / <span>Envato Pty Ltd</span></p>
                <div class="image_statements"><img src="images/stat1.jpg" alt=""></div>
            </div>
            <div class="item">
                <p class="text_statements">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                <p class="name_statements">Alissia Cronenberg / <span>Envato Pty Ltd</span></p>
                <div class="image_statements"><img src="images/stat2.jpg" alt=""></div>
            </div>
            <div class="item">
                <p class="text_statements">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                <p class="name_statements">Edward Swan / <span>Envato Pty Ltd</span></p>
                <div class="image_statements"><img src="images/stat3.jpg" alt=""></div>
            </div>
        </div>
    </div>
</div>