<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title><?= $this->e($title) ?></title>
    <meta name="description" content="">

    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2">
    <link rel="shortcut icon" href="<?= URL . 'images/favicon.ico' ?>" type="image/x-icon">
    <!-- Main style-->
    <link rel="stylesheet" href="<?= URL . 'css/style.css' ?>">
    <link rel="stylesheet" href="<?= URL . 'css/responsive.css' ?>">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="<?= URL . 'css/bootstrap.min.css' ?>">
    <link rel="stylesheet" href="<?= URL . 'css/animate.min.css' ?>">
    <!-- Owl carousel -->
    <link rel="stylesheet" href="<?= URL . 'css/owl.carousel.min.css' ?>">
    <link rel="stylesheet" href="<?= URL . 'css/owl.theme.default.min.css' ?>">
    <!-- Google Font -->
    <link href="<?= URL . 'https://fonts.googleapis.com/css?family=Karla:400,400i,700' ?>" rel="stylesheet">
    <link rel="stylesheet" href="<?= URL . 'css/fontawesome.css' ?>">
    <link rel="stylesheet" href="<?= URL . 'css/simple-line-icons.css' ?>">
    <!-- Fancybox -->
    <link rel="stylesheet" href="<?= URL . 'css/jquery.fancybox.css' ?>">

    <?php $this->section('styles') ?>

</head>


<body>

    <?php include MAINPATH . 'app/views/layouts/partials/_header.phtml' ?>
    <?php include MAINPATH . 'app/views/layouts/partials/_hero.phtml' ?>

    <?= $this->section('contents') ?>

    <?php include MAINPATH . 'app/views/layouts/partials/_footer.phtml' ?>

    <!-- ToTop -->
    <div id="content" class="site-content">
        <div id="toTop"> <i class="fa fa-chevron-up"></i> </div>
    </div>

    <?= $this->section('myModal') ?>

    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="<?= URL . 'js/jquery-2.2.4.js' ?>"></script>
    <script src="<?= URL . 'js/typed.min.js' ?>"></script>
    <script src="<?= URL . 'js/jquery.spincrement.min.js' ?>"></script>
    <script src="<?= URL . 'js/isotope.pkgd.js' ?>"></script>
    <script src="<?= URL . 'js/owl.carousel.min.js' ?>"></script>
    <script src="<?= URL . 'js/bootstrap.min.js' ?>"></script>
    <script src="<?= URL . 'js/jquery.fancybox.js' ?>"></script>
    <script src="<?= URL . 'js/contact.js' ?>"></script>
    <script src="<?= URL . 'js/script.js"' ?>></script>

    <!-- Yandex.Metrika counter -->
    <script type=" text/javascript">
        (function(m, e, t, r, i, k, a) {
            m[i] = m[i] || function() {
                (m[i].a = m[i].a || []).push(arguments)
            };
            m[i].l = 1 * new Date();
            k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
        })
        (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

        ym(51509117, "init", {
            id: 51509117,
            clickmap: true,
            trackLinks: true,
            accurateTrackBounce: true,
            webvisor: true
        });
    </script>

    <?= $this->section('scripts') ?>
</body>

</html>